# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c79e36dcaefd621b6deb59dbffe44f4850365a329570e74681d79d32229c759e0759e483e42d7e2ced7538656f89d8ab10aea77a9780e60e500bd5628d47dc3d

test:
  secret_key_base: 6eeb7ce42114099f8f236a79e41c86850d0eb494961fe7df84fdd2c08db891da9058682d16e08fced87fafae592fee0d5ae08ca401d37d6e2acc3fd1e3a56431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
